### PR TITLE
Specify delay with query params

### PR DESCRIPTION
**Pull request by yurikoval**
Specifying wait time `wait_before_screenshot_ms=300` (in ms) when capturing screenshots after the page is loaded.

```
https://example.vercel.app/api/capture?wait_before_screenshot_ms=300&url=https://alerts.in.ua/?minimal&disableInteractiveMap
```

The default delay is 300ms.

### CODE REVIEW

**Comment by robvanderleek** [comment]
Hi @yurikoval 

Thanks for the PR!

It works OK for the serverless part of the code.
However, your `delay` parameter conflicts with the `delay` parameter in the [standalone part of the code](https://github.com/robvanderleek/capture-website-api/blob/f477827a9365459b24f1bbc549b5151430ea0825/standalone/src/helpers.js#L30) (that uses the [capture-website library](https://github.com/sindresorhus/capture-website#delay)).

Can you resolve this issue? Perhaps rename your option?
Also, please make a small note about the parameter in the README.

Thanks!
KR, Rob

**Comment by yurikoval** [comment]
Hey Rob, since `capture-website` and my proposal are doing the same thing, I'm considering removing my changes from the standalone version, and standardizing the delay units, but keeping the same variable. What do you think about this approach? Do you think changing the variable name altogether is still better?

**Comment by robvanderleek** [comment]
HI @yurikoval 

Based on the capture-website Readme the `delay` parameter is in seconds, your parameter is in milliseconds.
If you can find a way around this I'm fine with it. Otherwise, picking a different name, or making sure the `delay` parameter does not reach the capture-website call is also fine.

Thanks for the effort.
Rob

**Comment by yurikoval** [comment]
Hey @robvanderleek 

I took your advice and renamed the parameter to `wait_before_screenshot_ms`. The current implementation defaults to 300ms for both standalone and serverless.

Thanks!

**Comment by robvanderleek** [comment]
Hi @yurikoval 👋 

Looks 👌 
Thanks for your contribution!

KR, Rob

**Pull request merged**
